name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 8
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -PgithubUser=$GITHUB_USERNAME -PgithubKey=$GITHUB_TOKEN
      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: artifacts/